project:
  type: website
  output-dir: docs

website: 
  title: "Shane A. Scaggs"
  navbar:
    background: "#3300ffcc"
    left:
      - about.qmd
      - CV.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
        
format:
  html:
    css: styles.css

editor: visual

