project:
  type: website
  output-dir: docs

website: 
  title: "Shane A. Scaggs"
  navbar:
    background: "#3300ff"
    left:
      - about.qmd
      - CV.qmd
      - posts.qmd
      - gallery.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      
format:
  html:
    css: styles.css

editor: visual

